# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:

    runs-on: [ windows-latest ]

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-win32-x64
        path: build/HTTPInterceptor-win32-x64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-win32-ia32
        path: build/HTTPInterceptor-win32-ia32.zip
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-win32-arm64
        path: build/HTTPInterceptor-win32-arm64.zip
  
  build-linux:

    runs-on: [ ubuntu-latest ]

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-linux-x64
        path: build/HTTPInterceptor-linux-x64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-linux-armv7l
        path: build/HTTPInterceptor-linux-armv7l.zip        
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-linux-ia32
        path: build/HTTPInterceptor-linux-ia32.zip        
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-linux-arm64
        path: build/HTTPInterceptor-linux-arm64.zip

  build-darwin:

    runs-on: [ macos-latest ]

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-darwin-x64
        path: build/HTTPInterceptor-darwin-x64.zip