# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:

    runs-on: [ windows-latest ]

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:ci --if-present
    - run: npm test
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-${{runner.os}}
        path: build/
  build-linux:

    runs-on: [ ubuntu-latest ]

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:ci --if-present
    - run: npm test
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-${{runner.os}}
        path: build/        
  build-macos:

    runs-on: [ macos-latest ]

    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    #- run: npm run build:ci --if-present
    - run: npm test
    - run: ls -la build/http_interceptor-darwin-x64
    - run: node zip.js
    - uses: actions/upload-artifact@v2
      with:
        name: http_interceptor-${{runner.os}}
        path: build/http_interceptor-darwin-x64.zip